### ISSUE TITLE
Change the PKGBUILD url to default to http://search.mcpan.org/

### ISSUE THREAD

**Issue by jnbek** [juster/perl-cpanplus-dist-arch#24]
MetaCPAN has a much nicer interface and many more features for Modules and Distributions.
When I cpan2aur Mojolicious, I get the url field:

url="http://search.cpan.org/dist/Mojolicious/"

This is fine I suppose, but I manually untar, :%s/>=0'/'/g and :%s/cpan\.org/mcpan\.org/g in the PKGBUILD and then run makepkg/mkaurball.
I recently came across a forum post where you suggested it may not be prudent to change the source field to use the mcpan.org for sources, I did some testing, search.mcpan.org redirects to cpan.metacpan.org and search.cpan.org to www.cpan.org. There may be more geo dns sniffing going on in there, but I've not dug into that and I'm not going to advocate either way it's speed benefit or anything like that between cpan.org or mcpan.org for the source field. In vim it's just easier to search replace all cpan.org to mpan.org to fix the two fields.
However, having the url field at least point to search.mcpan.org would make it nicer to check from the AUR perl-$package-name page. Check for new dependencies straight from the module's homepage, etc, before ever running cpan2aur. I have a build server I'm working on, but in the end, I still prefer to spend the time checking out Changelogs, etc before blindly updating a perl package and right now, especially for my older pkgbuilds, or pkgbuilds I adopt, I have to 'correct' the url in the browser address bar to the search.mcpan.org equivalent to get to the nice 21st century way to view CPAN ;-)

In the code, it'd be a simple matter of:

$url_field =~ s/cpan\./mcpan\./;

to acquiesce the proposal. While more research could be done on the source URL to see what kind of geographic adjustments are being made between search.cpan.org and metacpan.org, for the time being I'd be happy with only the url field in the PKGBUILD.

**Comment by juster** [comment]
Sure, might as well. I'll close this issue after I do it.

**Comment by jnbek** [comment]
:D thanks sir, you're awesome.

**Comment by juster** [comment]
Added in 1.30.
